display project Id - Status
PowerOfCreation/E1Ressourcenverwaltung pull request #64
Opened 2022-05-11 12:34 UTC by Vinh911

Tabelle zeigt die ProjektId an.
Nächsten Issues: 
- add_status.php an frontend anbinden
- Projekt Namen anzeigen
- Kalenderwoche ändern

2022-05-11 15:35 UTC, PowerOfCreation requested changes

2022-05-11 15:35 UTC, PowerOfCreation commented on src/webserver/api/get_calendar_week.php
> +        echo json_encode($dates_of_this_week);
```suggestion
        return $dates_of_this_week;
```

2022-05-11 15:35 UTC, PowerOfCreation commented on src/webserver/api/get_calendar_week.php
> +        get_calendar_week($week, $format);
Wenn du es so änderst  wie vorgeschlagen, dann musst du es so ersetzen:
```suggestion
        echo json_encode(get_calendar_week($week, $format));
```

2022-05-11 15:35 UTC, PowerOfCreation commented on src/webserver/api/get_calendar_week.php
> +        if(!isset($_GET["calendarWeek"]) || empty($_GET["calendarWeek"])) {
Probier mal das hier bitte
```suggestion
        if(empty($_GET["calendarWeek"])) {
```

2022-05-11 15:35 UTC, PowerOfCreation commented on src/webserver/js/weekly-report.js
> +    function getDates() {
Schön, dass du dafür Funktionen erstellt hast, dass können wir sicherlich gut wiederverwenden.

2022-05-11 15:35 UTC, PowerOfCreation commented on src/webserver/js/weekly-report.js
> +            $.get("api/get_all_weekly_status.php?calendarWeek=" + calendarWeek + "&year=" + year).done(function (data) {
Wenn du magst schau dir mal das hier an: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2022-05-12 17:27 UTC, Vinh911 commented on src/webserver/js/weekly-report.js
> -        if($(this).find("#add-project-select").length == 0)
Komisch, ich hab eigentlich kein Formater mehr. Ich beobachte das mal und schau mir die Dateien an, bevor ich commite.

2022-05-12 20:24 UTC, PowerOfCreation commented on src/webserver/api/get_calendar_week.php
> +    if (basename(__FILE__) == basename($_SERVER["SCRIPT_FILENAME"])) {
```suggestion
    if (__FILE__ == $_SERVER["SCRIPT_FILENAME"]) {
```
so? geht das?

2022-05-13 13:31 UTC, Vinh911 commented on src/webserver/api/get_calendar_week.php
> +    if (basename(__FILE__) == basename($_SERVER["SCRIPT_FILENAME"])) {
hab es gerade getestet. Funktioniert :)

2022-05-13 14:37 UTC, PowerOfCreation approved these changes

2022-05-13 14:37 UTC, merged